@extends('layouts.app')

@section('header-title', __('Payout Management'))
@section('header-subtitle', __('User guide and compensation plan documentation.'))

@section('content')
{{-- Sub-Navigation Hub --}}
@include('admin.payout.partials._nav')

<!-- Overview Banner -->
<div class="card border-0 shadow-sm rounded-12 mb-4 bg-primary text-white overflow-hidden position-relative" style="background: linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%);">
    <div class="card-body p-4">
        <div class="row align-items-center">
            <div class="col-lg-8">
                <span class="badge bg-white text-primary px-3 py-2 rounded-pill fw-bold mb-2">{{ __('MLM Compensation Plan') }}</span>
                <h3 class="fw-bold mb-2">{{ __('Dual-Phase Monthly Payout Architecture') }}</h3>
                <p class="mb-0 opacity-90 leading-relaxed">
                    {{ __('Janmitram calculates shop owner earnings through a combined Dual-Phase compensation model: Phase 1 rewards direct personal sales, while Phase 2 rewards downline group sales performance across 5 achievement tiers.') }}
                </p>
            </div>
            <div class="col-lg-4 text-lg-end mt-3 mt-lg-0">
                <i class="fas fa-network-wired fa-5x opacity-25"></i>
            </div>
        </div>
    </div>
</div>

<!-- Phase Breakdown Cards -->
<div class="row g-4 mb-4">
    <div class="col-md-6">
        <div class="card border-0 shadow-sm rounded-12 h-100 bg-white">
            <div class="card-body p-4">
                <div class="d-flex align-items-center gap-3 mb-3">
                    <div class="p-3 bg-primary-subtle text-primary rounded-12">
                        <i class="fas fa-user-check fs-3"></i>
                    </div>
                    <div>
                        <h5 class="fw-bold mb-0 text-dark">{{ __('Phase 1: Personal Sales Commission') }}</h5>
                        <small class="text-muted">{{ __('Direct earnings on own shop sales') }}</small>
                    </div>
                </div>
                <p class="text-muted mb-3">
                    {{ __('Every active shop owner earns a flat 10% commission on all Delivered orders generated by their shop during the billing month.') }}
                </p>
                <div class="p-3 bg-light rounded-12 border d-flex justify-content-between align-items-center">
                    <span class="fw-semibold text-dark">{{ __('Commission Rate') }}</span>
                    <span class="badge bg-primary fs-6 px-3 py-2 rounded-pill">10.0% {{ __('of Delivered Orders') }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card border-0 shadow-sm rounded-12 h-100 bg-white">
            <div class="card-body p-4">
                <div class="d-flex align-items-center gap-3 mb-3">
                    <div class="p-3 bg-success-subtle text-success rounded-12">
                        <i class="fas fa-users-cog fs-3"></i>
                    </div>
                    <div>
                        <h5 class="fw-bold mb-0 text-dark">{{ __('Phase 2: Group Sales Tiers') }}</h5>
                        <small class="text-muted">{{ __('Downline network bonus') }}</small>
                    </div>
                </div>
                <p class="text-muted mb-3">
                    {{ __('Shop owners who build downline networks qualify for Tiered bonuses based on cumulative Group Sales and minimum Team Size requirements.') }}
                </p>
                <div class="p-3 bg-light rounded-12 border d-flex justify-content-between align-items-center">
                    <span class="fw-semibold text-dark">{{ __('Achievement Levels') }}</span>
                    <span class="badge bg-success fs-6 px-3 py-2 rounded-pill">L0 {{ __('through') }} L4</span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Tier Matrix Table Card -->
<div class="card border-0 shadow-sm rounded-12 mb-4 bg-white">
    <div class="card-header bg-white py-3 border-bottom d-flex justify-content-between align-items-center flex-wrap gap-2">
        <div>
            <h5 class="card-title mb-0 fw-bold">{{ __('Phase 2 Tier Compensation Matrix') }}</h5>
            <small class="text-muted">{{ __('Evaluated lowest level first on qualifying Group Sales and Group Size.') }}</small>
        </div>
        <span class="badge bg-light text-dark border px-3 py-2 rounded-pill">{{ __('5 Achievement Tiers') }}</span>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th class="ps-4">{{ __('Level') }}</th>
                        <th>{{ __('Rank Title') }}</th>
                        <th>{{ __('Min Group Sales') }}</th>
                        <th>{{ __('Max Group Sales') }}</th>
                        <th class="text-center">{{ __('Min Team Size') }}</th>
                        <th class="text-end">{{ __('Commission / Calculation') }}</th>
                        <th class="text-end pe-4">{{ __('Max Level Cap') }}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L0</span>
                        </td>
                        <td class="fw-bold text-dark">{{ __('Star Promoter') }}</td>
                        <td class="fw-semibold text-dark">₹33,000</td>
                        <td class="text-muted">₹75,000</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 10 {{ __('shops') }}</span></td>
                        <td class="text-end fw-bold text-success">₹3,000 {{ __('Flat Bonus') }}</td>
                        <td class="text-end pe-4 text-muted">—</td>
                    </tr>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L1</span>
                        </td>
                        <td class="fw-bold text-dark">{{ __('Silver Associate') }}</td>
                        <td class="fw-semibold text-dark">₹75,000</td>
                        <td class="text-muted">₹300,000</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 10 {{ __('shops') }}</span></td>
                        <td class="text-end fw-bold text-success">4.0% {{ __('of Group Sales') }}</td>
                        <td class="text-end pe-4 text-muted">—</td>
                    </tr>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L2</span>
                        </td>
                        <td class="fw-bold text-dark">{{ __('Gold Leader') }}</td>
                        <td class="fw-semibold text-dark">₹300,000</td>
                        <td class="text-muted">₹3,000,000</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 100 {{ __('shops') }}</span></td>
                        <td class="text-end fw-bold text-success">1.0% {{ __('of Group Sales') }}</td>
                        <td class="text-end pe-4 text-muted">—</td>
                    </tr>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L3</span>
                        </td>
                        <td class="fw-bold text-dark">{{ __('Diamond Director') }}</td>
                        <td class="fw-semibold text-dark">₹3,000,000</td>
                        <td class="text-muted">₹30,000,000</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 10,000 {{ __('shops') }}</span></td>
                        <td class="text-end fw-bold text-success">0.2% {{ __('of Group Sales') }}</td>
                        <td class="text-end pe-4 text-muted">—</td>
                    </tr>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L4</span>
                        </td>
                        <td class="fw-bold text-dark">{{ __('Crown Ambassador') }}</td>
                        <td class="fw-semibold text-dark">₹30,000,000+</td>
                        <td class="text-muted">—</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 100,000 {{ __('shops') }}</span></td>
                        <td class="text-end fw-bold text-success">0.04% {{ __('of Group Sales') }}</td>
                        <td class="text-end pe-4 fw-bold text-danger">₹150,000 {{ __('Cap') }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Operational Rules & Lifecycle -->
<div class="row g-4">
    <div class="col-md-6">
        <div class="card border-0 shadow-sm rounded-12 h-100 bg-white">
            <div class="card-body p-4">
                <div class="d-flex align-items-center gap-3 mb-3">
                    <div class="p-3 bg-warning-subtle text-warning rounded-12">
                        <i class="fas fa-user-clock fs-3"></i>
                    </div>
                    <div>
                        <h5 class="fw-bold mb-0 text-dark">{{ __('90-Day Inactivity Lifecycle') }}</h5>
                        <small class="text-muted">{{ __('Automated member retention rule') }}</small>
                    </div>
                </div>
                <p class="text-muted small leading-relaxed">
                    {{ __('To protect the active network, members with no Delivered orders in the last 90 days are automatically detached on the 1st of every month via scheduler (00:00). Their direct downlines are cleanly reparented as new roots without losing downline tree integrity.') }}
                </p>
                <div class="bg-light p-3 rounded-12 border small text-muted">
                    <i class="fas fa-terminal text-primary me-1"></i>
                    <code>php artisan mlm:deactivate-inactive</code>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card border-0 shadow-sm rounded-12 h-100 bg-white">
            <div class="card-body p-4">
                <div class="d-flex align-items-center gap-3 mb-3">
                    <div class="p-3 bg-primary-subtle text-primary rounded-12">
                        <i class="fas fa-calendar-check fs-3"></i>
                    </div>
                    <div>
                        <h5 class="fw-bold mb-0 text-dark">{{ __('Monthly Execution Procedure') }}</h5>
                        <small class="text-muted">{{ __('How admin processes payouts') }}</small>
                    </div>
                </div>
                <ol class="small text-muted ps-3 mb-3 leading-relaxed">
                    <li class="mb-1">{{ __('Navigate to "Run Payout" and select target billing month.') }}</li>
                    <li class="mb-1">{{ __('Review live tree calculations and projected totals.') }}</li>
                    <li>{{ __('Click "Confirm & Execute Payout" — snapshots are saved and vendor wallets are credited atomically.') }}</li>
                </ol>
                <div class="bg-light p-3 rounded-12 border small text-muted">
                    <i class="fas fa-terminal text-primary me-1"></i>
                    <code>php artisan mlm:calculate-payouts --month=M --year=Y</code>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
