@extends('layouts.app')

@section('header-title', __('Payout Management'))
@section('header-subtitle', __('User guide and compensation plan documentation.'))

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-2">
    <div>
        <h4 class="fw-bold mb-1 text-dark">{{ __('Payout User Guide & Compensation Plan') }}</h4>
        <p class="text-muted small mb-0">{{ __('Complete operational manual, tier matrix, and system rules for managing MLM payouts.') }}</p>
    </div>
    <div class="d-flex gap-2 flex-wrap">
        @hasPermission('admin.payout.network')
            <a href="{{ route('admin.payout.network') }}" class="btn btn-outline-primary shadow-sm">
                <i class="fas fa-sitemap me-1"></i> {{ __('Payout Network') }}
            </a>
        @endhasPermission
        @hasPermission('admin.payout.index')
            <a href="{{ route('admin.payout.index') }}" class="btn btn-outline-secondary shadow-sm">
                <i class="fas fa-history me-1"></i> {{ __('Payout History') }}
            </a>
        @endhasPermission
        @hasPermission('admin.payout.run')
            <a href="{{ route('admin.payout.run.form') }}" class="btn btn-primary shadow-sm">
                <i class="fas fa-play me-1"></i> {{ __('Run Payout') }}
            </a>
        @endhasPermission
    </div>
</div>

<!-- Overview Banner -->
<div class="card border-0 shadow-sm rounded-12 mb-4 bg-primary text-white overflow-hidden position-relative">
    <div class="card-body p-4">
        <div class="row align-items-center">
            <div class="col-lg-8">
                <span class="badge bg-white text-primary px-3 py-2 rounded-pill fw-bold mb-2">{{ __('MLM Compensation Plan') }}</span>
                <h3 class="fw-bold mb-2">{{ __('Dual-Phase Monthly Payout Structure') }}</h3>
                <p class="mb-0 opacity-90 leading-relaxed">
                    {{ __('Janmitram calculates shop owner earnings through a combined Dual-Phase compensation model: Phase 1 rewards direct personal sales, while Phase 2 rewards downline group sales performance across 5 achievement tiers.') }}
                </p>
            </div>
            <div class="col-lg-4 text-lg-end mt-3 mt-lg-0">
                <i class="fas fa-network-wired fa-5x opacity-25"></i>
            </div>
        </div>
    </div>
</div>

<!-- Phase Breakdown Cards -->
<div class="row g-4 mb-4">
    <div class="col-md-6">
        <div class="card border-0 shadow-sm rounded-12 h-100">
            <div class="card-body p-4">
                <div class="d-flex align-items-center gap-3 mb-3">
                    <div class="p-3 bg-primary-subtle text-primary rounded-12">
                        <i class="fas fa-user-check fs-3"></i>
                    </div>
                    <div>
                        <h5 class="fw-bold mb-0 text-dark">{{ __('Phase 1: Personal Sales Commission') }}</h5>
                        <small class="text-muted">{{ __('Direct earnings on own shop sales') }}</small>
                    </div>
                </div>
                <p class="text-muted mb-3">
                    {{ __('Every active shop owner earns a flat 10% commission on all Delivered orders generated by their shop during the billing month.') }}
                </p>
                <div class="p-3 bg-light rounded-12 border d-flex justify-content-between align-items-center">
                    <span class="fw-semibold text-dark">{{ __('Commission Rate') }}</span>
                    <span class="badge bg-primary fs-6 px-3 py-2 rounded-pill">10.0% {{ __('of Personal Sales') }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card border-0 shadow-sm rounded-12 h-100">
            <div class="card-body p-4">
                <div class="d-flex align-items-center gap-3 mb-3">
                    <div class="p-3 bg-success-subtle text-success rounded-12">
                        <i class="fas fa-users-cog fs-3"></i>
                    </div>
                    <div>
                        <h5 class="fw-bold mb-0 text-dark">{{ __('Phase 2: Group Sales Tiers') }}</h5>
                        <small class="text-muted">{{ __('Downline network bonus') }}</small>
                    </div>
                </div>
                <p class="text-muted mb-3">
                    {{ __('Shop owners who build downline networks qualify for Tiered bonuses based on cumulative Group Sales and minimum Group Size requirements.') }}
                </p>
                <div class="p-3 bg-light rounded-12 border d-flex justify-content-between align-items-center">
                    <span class="fw-semibold text-dark">{{ __('Achievement Levels') }}</span>
                    <span class="badge bg-success fs-6 px-3 py-2 rounded-pill">L0 {{ __('through') }} L4</span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Tier Matrix Table Card -->
<div class="card border-0 shadow-sm rounded-12 mb-4">
    <div class="card-header bg-white py-3 border-bottom d-flex justify-content-between align-items-center">
        <h5 class="card-title mb-0 fw-bold">{{ __('Phase 2 Tier Compensation Matrix') }}</h5>
        <span class="badge bg-light text-dark border">{{ __('5 Achievement Tiers') }}</span>
    </div>
    <div class="card-body p-0">
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th class="ps-4">{{ __('Level') }}</th>
                        <th>{{ __('Min Group Sales') }}</th>
                        <th>{{ __('Max Group Sales') }}</th>
                        <th class="text-center">{{ __('Min Group Size') }}</th>
                        <th class="text-end">{{ __('Commission / Calculation') }}</th>
                        <th class="text-end pe-4">{{ __('Max Level Cap') }}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L0</span>
                        </td>
                        <td class="fw-semibold text-dark">₹33,000</td>
                        <td class="text-muted">₹75,000</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 10</span></td>
                        <td class="text-end fw-bold text-success">₹3,000 {{ __('Flat Bonus') }}</td>
                        <td class="text-end pe-4 text-muted">—</td>
                    </tr>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L1</span>
                        </td>
                        <td class="fw-semibold text-dark">₹75,000</td>
                        <td class="text-muted">₹300,000</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 10</span></td>
                        <td class="text-end fw-bold text-success">4.0% {{ __('of Group Sales') }}</td>
                        <td class="text-end pe-4 text-muted">—</td>
                    </tr>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L2</span>
                        </td>
                        <td class="fw-semibold text-dark">₹300,000</td>
                        <td class="text-muted">₹3,000,000</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 100</span></td>
                        <td class="text-end fw-bold text-success">1.0% {{ __('of Group Sales') }}</td>
                        <td class="text-end pe-4 text-muted">—</td>
                    </tr>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L3</span>
                        </td>
                        <td class="fw-semibold text-dark">₹3,000,000</td>
                        <td class="text-muted">₹30,000,000</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 10,000</span></td>
                        <td class="text-end fw-bold text-success">0.2% {{ __('of Group Sales') }}</td>
                        <td class="text-end pe-4 text-muted">—</td>
                    </tr>
                    <tr>
                        <td class="ps-4">
                            <span class="badge bg-success-subtle text-success border border-success-subtle rounded-pill px-3 py-2 fw-bold">L4</span>
                        </td>
                        <td class="fw-semibold text-dark">₹30,000,000</td>
                        <td class="text-muted">{{ __('No Limit') }}</td>
                        <td class="text-center"><span class="badge bg-light text-dark border">≥ 100,000</span></td>
                        <td class="text-end fw-bold text-success">0.04% {{ __('of Group Sales') }}</td>
                        <td class="text-end pe-4 fw-bold text-danger">₹150,000 {{ __('Cap') }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Workflow & Operations Section -->
<div class="row g-4 mb-4">
    <div class="col-md-4">
        <div class="card border-0 shadow-sm rounded-12 h-100">
            <div class="card-body p-4">
                <div class="text-primary mb-3">
                    <i class="fas fa-sitemap fs-1"></i>
                </div>
                <h5 class="fw-bold text-dark mb-2">{{ __('1. Payout Network') }}</h5>
                <p class="text-muted small mb-3">
                    {{ __('Hierarchical tree view of all active shop networks. Explore downlines, inspect personal vs group sales, and verify tier levels.') }}
                </p>
                <ul class="small text-muted ps-3 mb-0">
                    <li>{{ __('Live preview for unpaid months') }}</li>
                    <li>{{ __('Authoritative snapshot for paid months') }}</li>
                    <li>{{ __('Lazy-loading AJAX expansion for large trees') }}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-0 shadow-sm rounded-12 h-100">
            <div class="card-body p-4">
                <div class="text-success mb-3">
                    <i class="fas fa-history fs-1"></i>
                </div>
                <h5 class="fw-bold text-dark mb-2">{{ __('2. Payout History') }}</h5>
                <p class="text-muted small mb-3">
                    {{ __('Historical audit ledger of all processed monthly payouts. Search by month or year to verify exact credited amounts.') }}
                </p>
                <ul class="small text-muted ps-3 mb-0">
                    <li>{{ __('Paginated snapshot list') }}</li>
                    <li>{{ __('Phase 1 & Phase 2 individual line items') }}</li>
                    <li>{{ __('Month & Year filter options') }}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-0 shadow-sm rounded-12 h-100">
            <div class="card-body p-4">
                <div class="text-warning mb-3">
                    <i class="fas fa-play-circle fs-1"></i>
                </div>
                <h5 class="fw-bold text-dark mb-2">{{ __('3. Run Payout') }}</h5>
                <p class="text-muted small mb-3">
                    {{ __('Review-then-confirm workflow. Inspect projected earnings before executing atomic wallet transactions for the selected month.') }}
                </p>
                <ul class="small text-muted ps-3 mb-0">
                    <li>{{ __('Atomic DB transactions per shop') }}</li>
                    <li>{{ __('Automatic wallet credit') }}</li>
                    <li>{{ __('Prevents double-payouts automatically') }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Special Rules Card -->
<div class="card border-0 shadow-sm rounded-12 mb-4">
    <div class="card-header bg-white py-3 border-bottom">
        <h5 class="card-title mb-0 fw-bold">{{ __('System Rules & Safeguards') }}</h5>
    </div>
    <div class="card-body p-4">
        <div class="row g-4">
            <div class="col-md-6">
                <div class="d-flex align-items-start gap-3">
                    <div class="p-2 bg-info-subtle text-info rounded-3">
                        <i class="fas fa-box-check fs-4"></i>
                    </div>
                    <div>
                        <h6 class="fw-bold text-dark mb-1">{{ __('Delivered Orders Only') }}</h6>
                        <p class="text-muted small mb-0">
                            {{ __('Only orders with status "Delivered" within the calendar month are included in personal and group sales calculations. Pending or cancelled orders are excluded.') }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="d-flex align-items-start gap-3">
                    <div class="p-2 bg-warning-subtle text-warning rounded-3">
                        <i class="fas fa-user-slash fs-4"></i>
                    </div>
                    <div>
                        <h6 class="fw-bold text-dark mb-1">{{ __('90-Day Auto-Deactivation Policy') }}</h6>
                        <p class="text-muted small mb-0">
                            {{ __('Shop owners with zero orders in the last 90 days are automatically deactivated. Their children are re-parented to root level to keep the network active.') }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
